### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by bomxacalaka** [s60sc/ESP32_AdBlocker#2]
01:47:32.942 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
01:47:32.942 -> configsip: 0, SPIWP:0xee
01:47:32.942 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
01:47:32.942 -> mode:DIO, clock div:1
01:47:32.942 -> load:0x3fff0030,len:1344
01:47:32.942 -> load:0x40078000,len:13864
01:47:32.942 -> load:0x40080400,len:3608
01:47:32.942 -> entry 0x400805f0
01:47:33.367 -> E (283) psram: PSRAM ID read error: 0xffffffff
01:47:33.367 -> 
01:47:33.367 -> [00:03:26.982 startStorage] File: /data/configs.txt, size: 1115
01:47:33.413 -> [00:03:26.983 startStorage] LittleFS: Total bytes 196608, Used bytes 20480
01:47:33.600 -> [00:03:26.988 startStorage] Sketch size 1263kB
01:47:33.600 -> [00:03:27.207 loadConfig] Load config
01:47:33.741 -> [00:03:27.340 onWiFiEvent] Wifi Station started, connecting to: Me
01:47:33.741 -> [00:03:27.341 onWiFiEvent] Wifi AP SSID: ESP_367A99 started, use 'http://192.168.4.1' to connect
01:47:33.741 -> [00:03:27.341 setWifiSTA] Wifi Station IP from DHCP
01:47:33.741 -> ..........[00:03:32.359 startPing] Started ping monitoring
01:47:38.747 -> [00:03:32.361 startWebServer] Starting web server on port: 80
01:47:38.794 -> Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
01:47:38.794 -> 
01:47:38.794 -> Core  1 register dump:
01:47:38.794 -> PC      : 0x400d3ceb  PS      : 0x00060f30  A0      : 0x800d304f  A1      : 0x3ffb27e0  
01:47:38.794 -> A2      : 0x00000021  A3      : 0x00000068  A4      : 0x3ffc5968  A5      : 0xf25f5ef1  
01:47:38.794 -> A6      : 0xfffffffe  A7      : 0x0000ff00  A8      : 0x00000002  A9      : 0x3ffb27c0  
01:47:38.794 -> A10     : 0x00000000  A11     : 0x00000001  A12     : 0x3ffc3c94  A13     : 0x00000000  
01:47:38.794 -> A14     : 0x00000000  A15     : 0x0000003c  SAR     : 0x0000001f  EXCCAUSE: 0x0000001d  
01:47:38.841 -> EXCVADDR: 0x00000000  LBEG    : 0x4008ade6  LEND    : 0x4008adf1  LCOUNT  : 0x00000000  
01:47:38.841 -> 
01:47:38.841 -> 
01:47:38.841 -> Backtrace:0x400d3ce8:0x3ffb27e00x400d304c:0x3ffb2800 0x400ec066:0x3ffb2820 
01:47:38.841 -> 
01:47:38.841 -> 
01:47:38.841 -> 
01:47:38.841 -> 
01:47:38.841 -> ELF file SHA256: 0000000000000000
01:47:38.841 -> 
01:47:38.841 -> Rebooting...
01:47:38.841 -> ets Jun  8 2016 00:22:57

**Comment by s60sc** [comment]
01:47:33.367 -> E (283) psram: PSRAM ID read error: 0xffffffff
