### ISSUE TITLE
Support DNS over TLS for upstream servers?

### ISSUE THREAD

**Issue by PhantomPhoton** [s60sc/ESP32_AdBlocker#3]
Thank you so much for this project. It's almost exactly what I want. My ISP tracks dns queries made, even to third parties, so I would like to set the upstream DNS to one that uses DNS over TLS or DNS over HTTPS, to protect my privacy some.

It doesn't seem like there's a way currently to enable upstream servers to use either of those features?

**Comment by s60sc** [comment]
Thanks
The app uses the arduino DNSServer library which doesnt support those features and after googling I cant see that anyone has tried with the esp32.

**Comment by PhantomPhoton** [comment]
Thank you for verifying. I appreciate your time.
